session_name: default
start_directory: ~/
windows:
  - window_name: home
    panes:
      - blank
    focus: True
  - window_name: repo_home
    start_directory: repos
    panes:
      - blank
  - window_name: config
    start_directory: .config
    panes:
      - blank
