#!/bin/zsh
# This hook is run after a new virtualenv is activated.
proj_name=$(echo $VIRTUAL_ENV|awk -F'/' '{print $NF}')
if [[ ! -d ${HOME}/repos/py/${proj_name} ]]; then
    mkdir ${HOME}/repos/py/${proj_name}

    # Move to directory to set up the project
    cd ${HOME}/repos/py/${proj_name}
    curl https://raw.githubusercontent.com/github/gitignore/master/Python.gitignore -o .gitignore
    echo "\n# Ignore Vim swap files\n*.swp" >> .gitignore
    echo "\n\n#Secrets are best untold\nsecret.py" >> .gitignore
    touch README

    # Set up git repository
    git init
    git config user.name "Scott Godbold"
    git config user.email "scgodbold@gmail.com"
else
    echo "Repo already exists"
fi
