#!/bin/sh

REPO_DIR="${HOME}/repos"
OMZSH_DIR="${HOME}/.oh-my-zsh"

install_tmux_plugin_manager() {
    if [ ! -d "${HOME}/.tmux/plugins/tpm" ]; then
        git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm
    fi
}

install_alacritty() {
    if [ ! -e /usr/local/bin/alacritty ]; then
        cd /usr/ports/x11/alacritty
	sudo make -DBATCH install clean
        cd ${previous_dir}
    fi
}

install_pkgs() {
    sudo pkg install -y vim neovim curl git tmux zsh python3 python36 py36-pip cmake direnv entr the_silver_searcher go symbola xclip
}

install_pip_pkgs() {
    sudo /usr/local/bin/pip-3.6 install envtpl ipython flake8 pylint tmuxp virtualenv virtualenvwrapper
}

build_directories() {
    mkdir -p ${REPO_DIR}/py
    mkdir -p ${REPO_DIR}/go
}

bootstrap_vim() {
    # Bootstrap vim plugins
    if command -v vim >/dev/null 2>&1; then
        echo "Bootstraping Vim"
        vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
    fi
}

main() {
    build_directories
    install_pkgs
    install_pip_pkgs
    install_alacritty
    install_tmux_plugin_manager
}

main
