#! /bin/bash
REPO_DIR="${HOME}/repos"
OMZSH_DIR="${HOME}/.oh-my-zsh"

BREW_PKGS=(
    "neovim"
    "python"
    "python3"
    "the_silver_searcher"
    "tmux"
    "yadm"
    "zplug"
    "zsh"
    "direnv"
    "entr"
)

PIP_PKGS=(
    "envtpl"
    "ipython"
    "flake8"
    "pylint"
    "virtualenv"
    "virtualenvwrapper"
    "tmuxp"
)

function install_tmux_plugin_manager() {
    if [ ! -d "${HOME}/.tmux/plugins/tpm" ]; then
        git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm
    fi
}

function install_brew() {
    # This will likely never be executed as brew is going to be used to install yadm but just in case
    if [ ! $(command -v brew) ]; then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    if [ ! $(brew tap | grep "caskroom/cask") ]; then
        brew tap caskroom/cask
    fi
}

function install_pkgs() {
    # Install brew packages and link them
    brew install $(printf " %s" "${BREW_PKGS[@]}")
    brew link python python3  # These are not linked by default and we want this

    sudo /usr/local/bin/pip3 install $(printf " %s" "${PIP_PKGS[@]}")
}

function install_alacritty() {
    if [ ! -e "/Applications/Alacritty.app" ]; then
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        git clone https://github.com/jwilm/alacritty.git "${REPO_DIR}/alacritty"
        cd "${REPO_DIR}/alacritty"
        ${HOME}/.cargo/bin/rustup override set stable
        ${HOME}/.cargo/bin/rustup update stable
        ${HOME}/.cargo/bin/cargo build --release
        make app
        cp -r target/release/osx/Alacritty.app /Applications/
    fi
}

function bootstrap_vim() {
    # Bootstrap vim plugins
    if command -v nvim >/dev/null 2>&1; then
        echo "Bootstraping Vim"
        nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
    fi
}

function build_directories() {
    mkdir -p ${REPO_DIR}/py
    mkdir -p ${REPO_DIR}/go
}

function main(){
    install_brew
    install_pkgs
    install_alacritty
    bootstrap_vim
    install_tmux_plugin_manager() {
    build_directories
}

main
